"""Create user_profile_weight_history table

Revision ID: 4a4195e47144
Revises: 4a5942c9ed49
Create Date: 2025-12-17 13:47:45.972882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a4195e47144'
down_revision = '4a5942c9ed49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('height_cm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height_cm', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('weight_kg', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
