"""update food_records schema

Revision ID: 4a5942c9ed49
Revises: 
Create Date: 2025-12-17 10:13:18.851454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a5942c9ed49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_records', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('consumed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumed_at', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('image_url', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
