"""Convert activity_level and goal_type to Enum

Revision ID: 64e94f8156f6
Revises: 4a4195e47144
Create Date: 2025-12-17 14:12:35.606022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64e94f8156f6'
down_revision = '4a4195e47144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('activity_level',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('sedentary', 'lightly_active', 'moderately_active', 'very_active', name='activitylevelenum'),
               existing_nullable=False)
        batch_op.alter_column('goal_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('lose_weight', 'maintain', 'gain_weight', name='goaltypeenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('goal_type',
               existing_type=sa.Enum('lose_weight', 'maintain', 'gain_weight', name='goaltypeenum'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('activity_level',
               existing_type=sa.Enum('sedentary', 'lightly_active', 'moderately_active', 'very_active', name='activitylevelenum'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
