"""add total_steps to daily_energy_logs

Revision ID: 77a8631c77c7
Revises: 8b714ca67bf1
Create Date: 2025-12-25 14:15:39.831352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a8631c77c7'
down_revision = '8b714ca67bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_energy_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_steps', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_energy_logs', schema=None) as batch_op:
        batch_op.drop_column('total_steps')

    # ### end Alembic commands ###
