"""add tdee and target_calorie to daily_energy_logs

Revision ID: 8b714ca67bf1
Revises: 64e94f8156f6
Create Date: 2025-12-17 15:19:41.666352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b714ca67bf1'
down_revision = '64e94f8156f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_energy_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tdee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_calorie', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_energy_logs', schema=None) as batch_op:
        batch_op.drop_column('target_calorie')
        batch_op.drop_column('tdee')

    # ### end Alembic commands ###
