"""add total_steps to daily_energy_logs- 2

Revision ID: f12b8d5fe45c
Revises: 77a8631c77c7
Create Date: 2025-12-25 14:36:10.871952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12b8d5fe45c'
down_revision = '77a8631c77c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_energy_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steps_calorie_out', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_energy_logs', schema=None) as batch_op:
        batch_op.drop_column('steps_calorie_out')

    # ### end Alembic commands ###
